CREATE TABLE filial
(
    id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome     VARCHAR2(100) NOT NULL,
    endereco VARCHAR2(200) NOT NULL
);

CREATE TABLE usuario
(
    id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome      VARCHAR2(100) NOT NULL,
    email     VARCHAR2(100) NOT NULL UNIQUE,
    senha     VARCHAR2(200) NOT NULL,
    role      VARCHAR2(20) NOT NULL CHECK (role IN ('GESTOR', 'FUNCIONARIO')),
    id_filial NUMBER NOT NULL,
    CONSTRAINT usuario_filial_fk FOREIGN KEY (id_filial) REFERENCES filial (id)
);

CREATE TABLE modelo_moto
(
    id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE moto
(
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    placa          VARCHAR2(7) NOT NULL UNIQUE,
    id_modelo_moto NUMBER NOT NULL,
    CONSTRAINT moto_modelo_fk FOREIGN KEY (id_modelo_moto) REFERENCES modelo_moto (id)
);

CREATE TABLE carrapato
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    codigo_serial VARCHAR2(50) NOT NULL UNIQUE,
    status        VARCHAR2(20) DEFAULT 'DISPONIVEL' CHECK (status IN ('DISPONIVEL', 'EM_USO', 'MANUTENCAO')),
    nivel_bateria NUMBER DEFAULT 100 CHECK (nivel_bateria BETWEEN 0 AND 100)
);

CREATE TABLE historico_moto_filial
(
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_moto      NUMBER NOT NULL,
    id_filial    NUMBER NOT NULL,
    id_carrapato NUMBER,
    data_entrada TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_saida   TIMESTAMP,
    status       VARCHAR2(20) DEFAULT 'ATIVA' CHECK (status IN ('ATIVA', 'FINALIZADA')),
    CONSTRAINT hist_moto_fk FOREIGN KEY (id_moto) REFERENCES moto (id),
    CONSTRAINT hist_filial_fk FOREIGN KEY (id_filial) REFERENCES filial (id),
    CONSTRAINT hist_carrapato_fk FOREIGN KEY (id_carrapato) REFERENCES carrapato (id)
);
